### ISSUE TITLE
Trailing comma causes SASS compile error

### ISSUE THREAD

**Issue by andykirk** [inuitcss/trumps.widths#14]
Hi Harry,

_trumps.widths.scss line 20: `5,` - the trailing comma gives me an error with grunt-contrib-sass:

```
Running "sass:dist" (sass) task
Syntax error: Invalid CSS after "    5,": expected expression (e.g. 1px, bold), was ") !default;"
        on line 21 of [...]/bower_components/inuit-widths/_trumps.widths.scss
        from line 152 of _styles/style.scss
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.
```

Removing the trailing comma fixes the issue.

Cheers

**Comment by csshugs** [comment]
@andykirk 
Did you try to update your Sass version? Maybe this will eliminate your error, and you could get it running for now, until the trailing comma is gone.

I'm running inuitcss with libsass, by the way and I'm not getting any errors.

**Comment by andykirk** [comment]
Thanks. Updated grunt-contrib-sass but forgot about sass itself. Updated that and now have a tonne of different errors.

Oh, well. Will fix and post back if I find real problems.

Cheers
